name: Build Docker Images

on: [push]

env:
  DOCKERHUB_IMAGE_NAME: tkgmomosheep/pyinstaller
  GITHUB_IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        python: ["py3"]
        architecture: ["win64"]

    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
       name: Login to DockerHub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.4.1
        with:
          images: |
            ${{ env.DOCKERHUB_IMAGE_NAME }}
            ghcr.io/${{ env.GITHUB_IMAGE_NAME }}
          flavor: |
            latest=auto
            suffix=-${{matrix.python}}-${{matrix.architecture}},onlatest=true
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          file: "Dockerfile-${{matrix.python}}-${{matrix.architecture}}"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
